<?php

/**
 * @file
 * Contains style_management.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\style_management\Controller;

/**
 * Implements hook_help().
 */
function style_management_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the style_management module.
    case 'help.page.style_management':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Simple description') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_css_alter().
 */
function style_management_css_alter(&$css, \Drupal\Core\Asset\AttachedAssetsInterface $assets) {

  $MainController = new Controller\MainController();

  $MainController->rebuildTree($css);
  $MainController->build();
  $MainController->alterCss($css);

}

/**
 * Implements hook_cache_flush().
 */
function style_management_cache_flush() {
  $MainController = new Controller\MainController();
  $MainController->build();
}

/**
 * Implements hook_preprocess_page().
 */
function style_management_preprocess_page(&$page) {
  $MainController = new Controller\MainController();
  $MainController->build();
}
